---
# tasks file for create-autoscaling-group
- name: Configure Auto Scaling Group
  ec2_asg:
    region                 : "{{ asg.region }}"
    name                   : "{{ asg.name }}"
    launch_config_name     : "{{ lc.name }}"
    availability_zones     : "{{ asg.availability_zones }}"
    health_check_type      : "{{ asg.health_check_type }}"
    health_check_period    : "{{ asg.health_check_period }}"
    load_balancers         : "{{ asg.load_balancers | default('[]') }}"
    desired_capacity       : "{{ asg.desired_capacity }}"
    default_cooldown       : "{{ asg.default_cooldown }}"
    vpc_zone_identifier    : "{{ asg.vpc }}"
    min_size               : "{{ asg.min_size }}"
    max_size               : "{{ asg.max_size }}"
    wait_timeout           : "{{ asg.timeout }}"
    state                  : present
    tags                   : "{{ asg.tags }}"
  register: asg_result

- name: Configure Scaling Policies
  ec2_scaling_policy:
    region                 : "{{ asg.region }}"
    name                   : "{{ item.value.policy_name }}"
    asg_name               : "{{ asg.name }}"
    adjustment_type        : "{{ item.value.adjustment_type }}"
    min_adjustment_step    : "{{ item.value.min_adjustment_step }}"
    scaling_adjustment     : "{{ item.value.scaling_adjustment }}"
    cooldown               : "{{ item.value.cooldown }}"
  with_dict: "{{ policy_alarm }}"
  register: sp_result

- name: Configure Metric Alarms
  ec2_metric_alarm:
    region                 : "{{ asg.region }}"
    name                   : "{{ item.value.metric_name }}"
    metric                 : "{{ item.value.type }}"
    namespace              : "{{ item.value.namespace }}"
    statistic              : "{{ item.value.statistic }}"
    comparison             : "{{ item.value.comparison }}"
    threshold              : "{{ item.value.threshold }}"
    period                 : "{{ item.value.period }}"
    evaluation_periods     : "{{ item.value.evaluation_periods }}"
    unit                   : "{{ item.value.unit }}"
    dimensions             :
      AutoScalingGroupName : "{{ asg.name }}"
    alarm_actions          :
      - "{{ sp_result.results[0].arn }}"
  with_dict: "{{ policy_alarm }}"

- name: Configure Metric Alarms and link to Scaling Policies
  ec2_metric_alarm:
    region                 : "{{ asg.region }}"
    name                   : "{{ item.name }}"
    state                  : present
    metric                 : "{{ metric.name }}"
    namespace              : "{{ metric.namespace }}"
    statistic              : "{{ metric.statistic }}"
    comparison             : "{{ item.comparison }}"
    threshold              : "{{ item.threshold }}"
    period                 : "{{ item.period }}"
    evaluation_periods     : "{{ item.evaluation_periods }}"
    unit                   : "{{ metric.unit }}"
    dimensions             :
      AutoScalingGroupName : "{{ asg.name }}"
    alarm_actions          : "{{ item.alarm_actions }}"
  with_items: "{{ metric_alarms }}"
  when: asg.max_size > 1
